language: c

cache:
  directories:
    - bin
    - build_dir
    - staging_dir

env:
  global:
    - MAKEFLAGS="-j 2"

install:
    - cp GB-PC1_defconfig .config

script:
    - make defconfig
    - make V=s

