language: c

cache:
  directories:
    - bin
    - build_dir
    - dl
    - staging_dir

env:
  global:
    - MAKEFLAGS="-j 2"
    - PATH="$TRAVIS_BUILD_DIR/staging_dir/host/bin:$TRAVIS_BUILD_DIR/staging_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/bin:$PATH"


install:
    - cp GB-PC1_defconfig .config

script:
    - make defconfig
    - make V=s

