language: c

cache:
  directories:
    - bin
    - build_dir
    - dl
    - staging_dir

env:
  global:
    - MAKEFLAGS="-j 2"
    - PATH="$TRAVIS_BUILD_DIR/staging_dir/host/bin:$TRAVIS_BUILD_DIR/staging_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/bin:$PATH"

stages:
  - configure
  - tools
  - toolchain
  - linux
  - packages

install:
  - ln -s staging_dir/.config .config

jobs:
  include:

    - stage: configure
      script:
        - cp GB-PC1_defconfig .config
        - make defconfig
        - mv .config staging_dir

    - stage: tools
      script:
        - scripts/stamprun.sh make tools/install

    - stage: toolchain
      script:
        - scripts/stamprun.sh make toolchain/install

    - stage: linux
      script:
        - scripts/stamprun.sh make linux/compile

    - stage: packages
      script:
        - make packages/cleanup
        - scripts/stamprun.sh make packages/compile

# vim:sts=2 sw=2:
