language: c

cache:
  directories:
    - bin
    - build_dir

env:
  global:
    - MAKEFLAGS="-j 2"

install:
    - ./scripts/feeds update
    - ./scripts/feeds install -a
    - cp GB-PC1_defconfig .config

script:
    - make defconfig
    - make V=s

